### ISSUE TITLE
Original Dataset Before Preprocessing

### ISSUE THREAD

**Issue by Gayathri16401** [MidasXIV/Spatial-Temporal-Analysis-of-Crime#3]
Hi Team, 

Can you please provide an Original Dataset that is used before preprocessing?

**Comment by MidasXIV** [comment]
Sorry for the delay was on vacation, @Gayathri16401 you can find the dataset [here](https://drive.google.com/file/d/1TGqLhfuDrqJfUQBojlxI-d4CN5bpoUUR/view)

**Comment by Gayathri16401** [comment]
@MidasXIV Thank you!

**Comment by MidasXIV** [comment]
@Gayathri16401 may I know what you're going to build ? I'm planning to update this project as well.
